version: '3.5'
services:
  dev:
    user: root
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
    - ./:/helix.spark/:rw
    - ~/.local/share/virtualenvs:/root/.local/share/virtualenvs:rw
    container_name: helix_spark_dev
    working_dir: /helix.spark
