version: '3.5'
services:
  dev:
    user: root
    build:
      dockerfile: minimal.Dockerfile
      context: .
    volumes:
    - ./:/helix.spark/:rw
    container_name: helix_spark_dev
    working_dir: /helix.spark
