name: Deploy Docker Image

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [created]

jobs:
  build_and_test:
    # The type of runner that the job will run on
    # uses https://github.com/apache/spark/blob/master/bin/docker-image-tool.sh
    # export ARCHS=--platform linux/arm/v7,linux/arm64/v8,linux/amd64

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
          # stored in /home/runner/.local/share/virtualenvs
      - name: create virtualenv folder
        run: |
          mkdir -p ~/.local      
          mkdir -p ~/.local/share      
          mkdir -p ~/.local/share/virtualenvs
      - uses: actions/setup-java@v1
        with:
          java-version: '15'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          file: minimal.Dockerfile
          tags: imranq2/helix.spark:${{ steps.previoustag.outputs.tag }}-slim
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: imranq2/helix.spark:${{ steps.previoustag.outputs.tag }}

