name: Deploy Docker Image

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [created]

jobs:
  build_and_test:
    # The type of runner that the job will run on
    # uses https://github.com/apache/spark/blob/master/bin/docker-image-tool.sh
    # export ARCHS=--platform linux/arm/v7,linux/arm64/v8,linux/amd64

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - uses: vemonet/setup-spark@v1
        with:
          spark-version: '3.1.1' # Exact version
          hadoop-version: '3.2'
      - run: spark-submit --version
      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build docker images
        run: |
          docker buildx create --use
          ls -halt $SPARK_HOME
          curl https://raw.githubusercontent.com/apache/spark/master/resource-managers/kubernetes/docker/src/main/dockerfiles/spark/Dockerfile.java17 --output $SPARK_HOME/kubernetes/dockerfiles/spark/Dockerfile.java17
          ls -halt $SPARK_HOME/kubernetes/dockerfiles/spark
          cat $SPARK_HOME/kubernetes/dockerfiles/spark/Dockerfile.java17
          $SPARK_HOME/bin/docker-image-tool.sh -r imranq2 -t ${{ steps.previoustag.outputs.tag }} -X -f $SPARK_HOME/kubernetes/dockerfiles/spark/Dockerfile.java17 -p $SPARK_HOME/kubernetes/dockerfiles/spark/bindings/python/Dockerfile -b java_image_tag=17-slim build
